name: GoWork schedule Server cleaning

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'

jobs:

  schedule-cleaning:
    runs-on: ubuntu-latest

    steps:

      - name: Docker all cache cleaning
        run: |
          echo "Hello World!"