name: GoWork CI/CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build and test Prod Environment
        run: docker-compose -f docker-compose.prod.yaml build

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-and-test ]

    concurrency: cd-${{ github.ref }}

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build and test Prod Environment
        run: docker-compose -f docker-compose.prod.yaml build