name: GoWork DB migration

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Migration filename to run'
        required: true

jobs:

  apply-migration:
    runs-on: ubuntu-latest

    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
