name: GoWork CI/CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

  workflow_run:
    workflows: [ "GoWork CI/CD" ]
    types: [ completed ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build and test Prod Environment
        run: docker-compose -f docker-compose.prod.yaml build
