name: GoWork CI/CD

on:
  push:
    branches: [ master, temp ]

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: build-and-test
        uses: whatnick/wait-action@master
        with:
          time: '90s'

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-and-test ]

    concurrency: cd-${{ github.ref }}

    steps:
      - name: deploy
        uses: whatnick/wait-action@master
        with:
          time: '90s'
