name: GoWork schedule Server cleaning

on:
  schedule:
    - cron: "3 0 12,26 * *"

jobs:

  schedule-cleaning:
    runs-on: ubuntu-latest

    steps:

      - name: Docker all cache cleaning
        run: |
          echo "Hello World!"